apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clouddevops-ingress
  namespace: ivolve
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: clouddevops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: clouddevops-svc
            port:
              number: 80
