apiVersion: v1
kind: Service
metadata:
  name: clouddevops-svc
  namespace: ivolve
spec:
  selector:
    app: clouddevops
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer
